version: '3.4'

services:
  hospitalmanagementsystem.api:
    image: ${DOCKER_REGISTRY-}hospitalmanagementsystemapi
    build:
      context: .
      dockerfile: src/Presentation/HospitalManagementSystem.API/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - hospitalmanagementsystem.database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=hospitalmanagementsystem.database,1433;Database=HospitalManagement;User=sa;Password=password@12345#;TrustServerCertificate=True;Encrypt=False;
   
  hospitalmanagementsystem.database:
    container_name: hospitalmanagementsystem.database
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    volumes:
      - dbdata:/var/opt/mssql

  hospitalmanagementsystem-blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: hospitalmanagementsystem.blob-storage
    volumes:
      - ./.containers/blob-storage/data:/data
    ports:
      - "10000:10000"
    command: "azurite-blob --blobHost 0.0.0.0 -l /data"

  hospitalmanagementsystem-mq:
    image: rabbitmq:3.11.7-management
    container_name: Queque
    hostname: hospitalmanagementsystem-queque
    volumes:
       - ./.containers/queque/data/:/var/lib/rabbitmq
       - ./.containers/queque/log/:/var/log/rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
volumes:
  dbdata:


    
